### ISSUE TITLE
SSL error while launching Empire Headless

### ISSUE THREAD

**Issue by tugdualnicolas** [interference-security/empire-web#18]
Input : `./empire --headless`

Output : 
```
[*] Loading stagers from: /root/Empire//lib/stagers/
[*] Loading modules from: /root/Empire//lib/modules/
[*] Loading listeners from: /root/Empire//lib/listeners/



* Starting Empire RESTful API on port: 1337
 * RESTful API token: *******************************************
Traceback (most recent call last):
  File "./empire", line 1359, in <module>
    start_restful_api(empireMenu=main, suppress=True, username=args.username, password=args.password, port=args.restport)
  File "./empire", line 1301, in start_restful_api
    context = ssl.SSLContext(proto)
AttributeError: 'module' object has no attribute 'SSLContext'

```

**Comment by interference-security** [comment]
This is an error with Empire project. Please file an issue here: https://github.com/EmpireProject/Empire
