### ISSUE TITLE
Error after starting RESTful API

### ISSUE THREAD

**Issue by leebaird** [interference-security/empire-web#2]
```
[*] Loading modules from: /opt/Empire/lib/modules/
 * Starting Empire RESTful API on port: 443
 * RESTful API token: kvru3y7ltipp21tjeu3lduy05wua9ahwaodzfntw
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file _internal.py, line 87
```

**Comment by interference-security** [comment]
Thank you for reporting @leebaird. This is an issue with PowerShell Empire and should be reported here: https://github.com/PowerShellEmpire/Empire/issues

PowerShell Empire Web utilizes the REST API provided by PowerShell Empire. Both are separate projects.
